name: Sync Fork Upstream

on:
  schedule:
    - cron: '0 0 * * 7'  # On sunday at midnight
  workflow_dispatch:     # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: AbdulmelikKalkan/sync-fork-upstream@v1.3
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          owner: DominikMe
          repo: acs-emulator
          branch: main
